### ISSUE TITLE
Unable to use Dependency Substitution

### ISSUE THREAD

**Issue by greg-bahr** [Pattonville-Robotics/2867#5]
It appears that we are unable to use dependency substitution with Common-Code due to a bug in gradle at the moment that prevents loading the android plugin multiple times in a single build. 
[https://developer.android.com/studio/build/gradle-plugin-3-0-0.html](https://developer.android.com/studio/build/gradle-plugin-3-0-0.html)

**Comment by magneticflux-** [comment]
>To resolve this issue for composite builds, you additionally need to make sure that, for the main project and each included project that uses the Android plugin, the buildscript classpaths are identical. This also requires the order of the classpaths you add to the buildscript block to be identical. For example, the following results in a build error:

It looks like we have to add `classpath 'com.github.dcendents:android-maven-gradle-plugin:2.0'` below the Android Gradle plugin for 2867. Can you test that fix @greg-bahr?
